name: Docker Image buildx by tag on alpine

on:
  push:
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10

env:
  # name of docker image
  DOCKER_HUB_USER: sinlov
  IMAGE_BUILD_OS_NAME: alpine
  IMAGE_NAME: drone-file-browser-plugin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release binary
      run: |
        make dep
        make distPlatformTarAllLinux
    - uses: softprops/action-gh-release@v1
      name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
#        body_path: ${{ github.workspace }}-CHANGELOG.txt
        prerelease: true
        # https://github.com/isaacs/node-glob
        files: |
          **/*.tar.gz
          **/*.sha256

