name: Docker Image buildx by tag on alpine

on:
  push:
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10

env:
  # name of docker image
  DOCKER_HUB_USER: sinlov
  IMAGE_BUILD_OS_NAME: alpine
  IMAGE_NAME: drone-file-browser-plugin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release binary
      run: |
        make dep
        make distPlatformTarAllLinux
    - uses: "marvinpinto/action-automatic-releases@latest"
      name: Create Release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
#        automatic_release_tag: "latest"
        prerelease: true
        title: "prerelease Build by tag"
        # https://github.com/isaacs/node-glob
        files: |
          **/*.tar.gz
          **/*.sha256

